// components/RootLayout.js

import type { Metadata } from 'next'
import { Inter, Playfair_Display, Raleway, DM_Sans } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const playfair = Playfair_Display({ subsets: ['latin'] })
const raleway = Raleway({ subsets: ['latin'] })
const dmsans = DM_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'sijadua',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${playfair.className} ${raleway.className} ${dmsans.className}`}>{children}</body>
    </html>
  )
}
